dir="$1"
vsdir="$1/vslib"
mkdir -pv "$vsdir"
cp	"./adjust/adjust.py"						"$vsdir/"
cp	"./CSMOD/CSMOD.py"							"$vsdir/"
cp	"./havsfunc/havsfunc.py"					"$vsdir/"
cp	"./mvsfunc/mvsfunc.py"						"$vsdir/"
cp	"./nnedi3_resample/nnedi3_resample.py"		"$vsdir/"
cp	"./pmsfunc/pmsfunc.py"						"$vsdir/"
cp	"./vsTAAmbk/vsTAAmbk.py"					"$vsdir/"
cp	"./loadlib.py"								"$dir/"
